---
title: "Events"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Damaged layout
```{r}
pilatus_layout <- create_module("Pilatus")

file_path <- "../tests/testthat/dead_pix/Pilatus/badpixel_mask.tif"

pilatus_layout <- load_pix_matrix(layout = pilatus_layout, file_path = file_path)

plot_layout_damaged(layout = pilatus_layout)
```
Classifying and plotting events
```{r}

pilatus_layout <- find_clumps(pilatus_layout)

plot_events(pilatus_layout)

plot_pixels_events(pilatus_layout)

plot_events(pilatus_layout, incl_event_list = 4)

plot_pixels_events(pilatus_layout, incl_event_list = 4)

```
### Selecting events for analysis
```{r}

plot_events(pilatus_layout, incl_event_list = list(2,3,4,5,6,7,8,9))

plot_pixels_events(pilatus_layout, incl_event_list = list(2,3,4,5,6,7,8,9))

```
### Plotting events density
```{r}

plot_events_density(pilatus_layout, incl_event_list = list(4))

```
### Selecting modules for events
```{r}

pilatus_layout <- find_clumps(pilatus_layout, row=5, col=1)

plot_events_density(pilatus_layout, incl_event_list = list(4))

```
