---
title: "Events"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Damaged detector
```{r}
pilatus_detector <- create_module("Pilatus")

file_path <- "../tests/testthat/dead_pix/Pilatus/badpixel_mask.tif"

pilatus_detector <- load_pix_matrix(detector = pilatus_detector, file_path = file_path)

plot_detector_damaged(detector = pilatus_detector)
```
```{r}

pilatus_detector_temp <- find_clumps(pilatus_detector)

plot_events(pilatus_detector_temp, caption = FALSE, incl_event_list = NA)
```

### Classifying and plotting events (Selecting events for analysis)
```{r}

pilatus_detector <- find_clumps(pilatus_detector)

plot_events(pilatus_detector)

plot_pixels_events(pilatus_detector)

plot_events(pilatus_detector, incl_event_list = 4)

plot_pixels_events(pilatus_detector, incl_event_list = 4)

plot_events(pilatus_detector, incl_event_list = list(2,3,4,5,6,7,8,9))

plot_pixels_events(pilatus_detector, incl_event_list = list(2,3,4,5,6,7,8,9))

```

### Plotting events density (selecting modules too)
```{r}

pilatus_detector_temp <- find_clumps(pilatus_detector)

plot_events_density(pilatus_detector_temp, caption = FALSE, incl_event_list = NA)
```

```{r}
pilatus_detector_temp <- find_clumps(pilatus_detector, row=5, col=1)

plot_events_density(pilatus_detector_temp, incl_event_list = list(4))

```
### Plotting counts
```{r}
pilatus_detector_temp <- find_clumps(pilatus_detector)

plot_events_count(pilatus_detector_temp, caption = FALSE)

```


### Plotting arrows (selecting modules too)
```{r}

pilatus_detector <- find_clumps(pilatus_detector)

plot_events_arrows(pilatus_detector, incl_event_list = list(4))

pilatus_detector <- find_clumps(pilatus_detector, row=5, col=1)

plot_events_arrows(pilatus_detector, incl_event_list = list(4))
```
### Plotting KFGs

```{r}
pilatus_detector <- find_clumps(pilatus_detector)

plot_events_kfg(pilatus_detector, func = "Kinhom", incl_event_list = list(4))

```
